const List<Map<String, dynamic>> assets = [
  {
    'name': 'Solana',
    'prefix': 'SOL',
    'image': 'solana.png',
    'id': 'solana',
  },
  {
    'name': 'Bitcoin',
    'prefix': 'BTC',
    'image': 'bitcoin.png',
    'id': 'bitcoin',
  },
  {
    'name': 'EOS',
    'prefix': 'EOS',
    'image': 'eos.png',
    'id': 'eos',
  },
  {
    'name': 'Ethereum',
    'prefix': 'ETH',
    'image': 'eth.png',
    'id': 'ethereum',
  },
  {
    'name': 'Binance USD',
    'prefix': 'BNB',
    'image': 'binance.png',
    'id': 'binance-usd',
  },
  {
    'name': 'Cardano',
    'prefix': 'ADA',
    'image': 'ada.png',
    'id': 'cardano',
  },
  {
    'name': 'Tether',
    'prefix': 'USDT',
    'image': 'usdt.png',
    'id': 'tether',
  },
  {
    'name': 'USD Coin',
    'prefix': 'USDC',
    'image': 'usdc.png',
    'id': 'usd-coin',
  },
  {
    'name': 'Stellar',
    'prefix': 'XLM',
    'image': 'xlm.png',
    'id': 'stellar',
  },
  {
    'name': 'Dogecoin',
    'prefix': 'doge',
    'image': 'doge.png',
    'id': 'dogecoin',
  },
  {
    'name': 'XRP',
    'prefix': 'XRP',
    'image': 'xrp.png',
    'id': 'ripple',
  },
  {
    'name': 'Ren',
    'prefix': 'REN',
    'image': 'ren.png',
    'id': 'republic-protocol',
  },
  {
    'name': 'Chainlink',
    'prefix': 'Link',
    'image': 'chainlink.png',
    'id': 'chainlink',
  },
  {
    'name': 'Terra',
    'prefix': 'LUNA',
    'image': 'luna.png',
    'id': 'terra-luna',
  },
];
