name: mobile2
description: Occam Wallet
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^1.6.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  iconify_flutter: ^0.0.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_screen/
    - assets/images/crypto_assets/
